### ISSUE TITLE
Publish wheel

### ISSUE THREAD

**Issue by alugowski** [pytroll/donfig#87]
Submitting as a user of a downstream package.

Could you please upload a wheel to PyPI in addition to the sdist?

The lack of a donfig wheel causes issues with pip's binary-only option. For example, if I install a package that depends on donfig like this:

```bash
pip install --only-binary ":all:" python-graphblas
```

then this results in:
```
The conflict is caused by:
    python-graphblas 2023.10.0 depends on donfig>=0.6
    python-graphblas 2023.7.0 depends on donfig>=0.6
...
```

pip is unable to install any version because there is no way to install donfig in a binary-only way.

The workaround is to first install donfig, but that's a manual step that shouldn't be necessary.

**Comment by djhoese** [comment]
I'm willing to do this and was actually just talking to someone about this recently at a presentation about python packaging. In my opinion, at least at the time, I did not see a reason to create a wheel for a pure python package. Your use case is an interesting one. For your usage, is there a reason you do "all" instead of only the package you are installing? I assume your reason for only-binary is to avoid having any packages compiled at install time?

**Comment by alugowski** [comment]
I use "all" because I don't want to build any transitive dependencies from source either.

**Comment by alugowski** [comment]
For reference, this workflow code builds both sdists and pure python wheels:

```yml
      - name: Build
        run: pipx run build

      - name: Check
        run: pipx run twine check dist/*

      - uses: pypa/gh-action-pypi-publish@release/v1

```
